name: Publish Debian Package

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Publish Package to GitHub Packages
        run: |
          echo "Publishing Debian package to GitHub Packages"
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh pkg publish ./blacksmith-cli-linux.deb
        env:
          DEBIAN_FRONTEND: noninteractive
        timeout-minutes: 15
