name: Build and publish Debian package

on:
  push:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Debian package
        run: dpkg-buildpackage -b

      - name: Publish Debian package
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: ./debian-pkg/*.deb
