name: Publish Debian Package for x86_64

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg

      - name: Publish Package to GitHub Packages
        run: |
          echo "Publishing Debian package to GitHub Packages for x86_64"
          sudo dpkg -i blacksmith-cli-${ARCH}.deb
        env:
          DEBIAN_FRONTEND: noninteractive
        timeout-minutes: 15
